# Generated by Django 2.1.5 on 2019-02-15 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('process', 'Обрабатывается'), ('shipped', 'Отправлено'), ('delivered', 'Доставлено')], default='process', max_length=20, verbose_name='Статус'),
        ),
    ]
